baseURL = 'https://fireactjs.com/'
languageCode = 'en-us'
title = 'Fireactjs'
[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"