baseURL = 'https://fireactjs.com/'
languageCode = 'en-us'
title = 'Fireactjs'
# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"
[params]
github_repo = "https://github.com/fireactjs/website"